### ISSUE TITLE
Locks up one core at 100%

### ISSUE THREAD

**Issue by bharathyes** [stsdc/monitor#107]
For the past day or two, one of my CPU cores have been randomly locked at 100% usage.

Even this monitor app would only show CPU usage at 22% or even less but the system would heat up with the fan running at full speed.

On running `htop` the command `com.github.stsdc.monitor` was listed as using 100% CPU with one of the cores locked at 100% and two more fluctuating close to the number. No other process was using any significant CPU.

**Comment by stsdc** [comment]
Was Monitor's indicator enabled?

**Comment by bharathyes** [comment]
Hi. Sorry for the late reply. Yes the indicator was enabled but it never showed 100% usage because I am guessing it only shows the overall average CPU usage. But on running htop I was shown one of the cores was using 100% without any fluctuation.

I have since moved to a different distro. I will try this once again if possible.

**Comment by stsdc** [comment]
@bharathyes but was it working properly? I'm wondering if it has something with other issue that hangs the Monitor and the Indicator.

**Comment by stsdc** [comment]
Looks like this is connected with #88
