### ISSUE TITLE
Flatpak Apps show up as "Background Applications"

### ISSUE THREAD

**Issue by RMcNeely** [stsdc/monitor#111]
## Feature Request:
Have Flatpak apps show up outside of "Background Application" tab in Monitor. 

Currently this is not a big deal, I have a handful of Flatpak apps that I'm using and I don't mind that the few that I use show up under Background Applications, in the future though as elementary moves to Flatpak for apps though, this will start to present a problem. Eventually everything will likely show up as a Flatpack and things will be harder to read. Ideally Monitor would have a way to display Flatpak apps and display them similarly to the way it displays other apps now.

I don't use Snaps but I imagine that there is probably a similar issue with the way that Snaps display as well.

### Current Behavior:
![image](https://user-images.githubusercontent.com/2806302/66094103-c36f8e80-e560-11e9-9bfb-4c5a697dcd4a.png)

**Comment by stsdc** [comment]
That's true. Snaps and Flatpak apps are showing like on screenshot above. And as far as I know, that is the limitation of libbamf. BAMF is a part of the Ayatana Project, and support of this project was dropped. Currently there is no alternative for libbamf. If someone knows any library that could replace the libbamf, paste link here.

**Comment by janxkoci** [comment]
I think this is not the case for a long time. I see flatpak apps normally even on Hera (5.1).

Consider closing.

**Comment by stsdc** [comment]
True.
