### ISSUE TITLE
Fix Travis CI build

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#117]

**Comment by ryonakano** [comment]
This is an issue of Houston which is already reported at https://github.com/elementary/houston/issues/751.

**Comment by ryonakano** [comment]
The referenced issue above seem to be fixed. I guess the build should succeed now and we can close this issue.

**Comment by stsdc** [comment]
Thank You, @ryonakano.

**Comment by stsdc** [comment]
Broken again :disappointed:

**Comment by ryonakano** [comment]
Yeah and I think this issue is elementary/houston#755 and it was closed in 757. But the error still happens… :thinking:
