### ISSUE TITLE
Show the current CPU frequency in hovering the CPU usage rate text

### ISSUE THREAD

**Issue by ryonakano** [stsdc/monitor#131]
![2019-11-03 23 09 34 の画面録画](https://user-images.githubusercontent.com/26003928/68086412-1f467380-fe8f-11e9-8dca-4896376c35ff.gif)

Hovering the CPU usage rate text does not show any tooltips at the moment unlike the memory or swap usage rates text, but I guess it would be useful to show the current CPU frequency.

**Comment by stsdc** [comment]
I can also see, that You have info about have many GiB the swap is using. And I don't have this 😅

**Comment by ryonakano** [comment]
> I can also see, that You have info about have many GiB the swap is using. And I don't have this :sweat_smile:

I had been using a laptop with 4GB memory and the total amount of physical memory isn't enough for me, so I built a new desktop PC with 16GB memory. :smiley:

**Comment by stsdc** [comment]
@ryonakano would You like to make a PR? :thinking:

**Comment by ryonakano** [comment]
Yes, I'd really like to and I tried when I posted this issue, but I'm not sure how we can show it :cry: I thought [`GTop.Cpu.frequency`](https://github.com/stsdc/monitor/blob/275290c3a42e1118efaf07fe9d7e47f8505c4728/vapi/libgtop-2.0.vapi#L108) has the value we want, but it does not seem to have…

**Comment by stsdc** [comment]
Here is [an amazing code](https://github.com/PlugaruT/wingpanel-monitor/blob/edcfea6a31f794aa44da6d8b997378ea1a8d8fa3/src/Services/Cpu.vala#L61-L85) of Tudor's Monitor Indicator.

**Comment by ryonakano** [comment]
Wow, I was also seeing that code. I opened this issue page just now and found you're faster to comment than me. Now work in progress.
