### ISSUE TITLE
Process and memory status disappear from the top-panel on ctrl+q shortcut.

### ISSUE THREAD

**Issue by yezhidal** [stsdc/monitor#137]
Showing memory and process status in the top panel works only if I close the app with UI 'X' button. When I close it with 'ctrl+q' shortcut, indicators disappear (because app closes).

**Comment by stsdc** [comment]
Intended behaviour:
ctrl-q to close the app
alt-f4 to close the window

**Comment by yezhidal** [comment]
Now I'm understand. Thank you for clarifying it.
