### ISSUE TITLE
Monitor crush

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#138]
Was trying to catch hanging issue, but caught this one:

`Gtk:ERROR:../../../../gtk/gtktreestore.c:596:gtk_tree_store_get_path: assertion failed: (G_NODE (iter->user_data)->parent != NULL)`

**Comment by mattperry1976** [comment]
I am running 0.6.1 and this is still happening

**Comment by stsdc** [comment]
Connected with #88
