### ISSUE TITLE
Redesign Monitor icon

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#15]
And adopt it for other sizes.

**Comment by png2378** [comment]
Why Monitor don't use [this](https://github.com/elementary/icons/blob/system-monitor/apps/128/utilities-system-monitor.svg) icon?

**Comment by zvirdaniel** [comment]
That's a pretty icon, I agree with @png2378

**Comment by stsdc** [comment]
Yeah, icon is great, but that icon is for system app. And Monitor isn't a system application. I think that's why Daniel forbids to use it. Look at #2.

**Comment by capstan1** [comment]
And what's wrong about the current one?

**Comment by stsdc** [comment]
Because, [that's how it should be done](https://elementary.io/docs/human-interface-guidelines#iconography).
 Current one is too dark, blurry and downscaled for another sizes. That's bad.

**Comment by lainsce** [comment]
May I help you with that? :wink: 
I did a Pull Request with some changes to your icons that are in accordance with the elementary HIG
