### ISSUE TITLE
Add switch for showing all processes

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#159]
This will require to prompt user password, since it is required to get info about IO operations.

**Comment by janxkoci** [comment]
There is such switch in similar apps (`lxtask` and `xfce4-taskmanager` I think) but they don't require passwords IIRC.

**Comment by stsdc** [comment]
Yes, it's because they don't show IO operations.

**Comment by janxkoci** [comment]
> it's because they don't show IO operations

I see, my bad.

**Comment by stsdc** [comment]
Monitor is now showing all processes by default.
