### ISSUE TITLE
Side panel cannot be closed

### ISSUE THREAD

**Issue by janxkoci** [stsdc/monitor#173]
What it says on the tin - side panel cannot be closed and blocks the view of running processes.

**Comment by stsdc** [comment]
It designed to be always opened. Why do You need to close it?

**Comment by 4jNsY6fCVqZv** [comment]
Funny, I don't know your app yet, but I had the same impulse while looking at the screenshot. Maybe the possibility to easily fold and unfold the sidebar is just a way to visually reduce the amount of information.

**Comment by janxkoci** [comment]
It's not opened when I launch the app. Then when I click some process, the sidebar opens on the right, partially blocking the view (e.g. columns with CPU and memory usage). Moreover the list view cannot be scrolled horizontally when it's covered by the sidebar. The only way to see all info is to resize the window, which I don't wanna do because my setup was perfect until now (as in OCD kind of perfect).

**Comment by stsdc** [comment]
If I'll add a close button, sidebar will open every time user chooses proces. It triggers showing sidebar. 

I'm aware that sidebar is not showing at startup (no process is chosen yet).

**Comment by ryonakano** [comment]
> I'm aware that sidebar is not showing at startup (no process is chosen yet).

Maybe we can address this by selecting the top row at startup.

**Comment by stsdc** [comment]
Yes,  I tried to do this, but failed. @ryonakano  could You make a pr?

**Comment by stsdc** [comment]
@ryonakano ping :eyes:

**Comment by ryonakano** [comment]
Sorry for the soooo late reply, I took a look but it does not seem to work as you said… I'll take another look.

**Comment by stsdc** [comment]
Yeah.. my code is a mess 😅️ sorry 😬️
