### ISSUE TITLE
Google Chrome is shown as WhatsApp

### ISSUE THREAD

**Issue by WebShapedBiz** [stsdc/monitor#174]
Hi.

I've installed an unofficial WhatsApp Electron desktop app and now all Chrome processes are shown as WhatsApp.
![Monitor](https://user-images.githubusercontent.com/6765137/80182307-e483f380-8606-11ea-82c7-b4f77fb086a2.png)
Cheers.

**Comment by stsdc** [comment]
how did you install whatsapp and google? are they snaps?

**Comment by WebShapedBiz** [comment]
Don't even have Snap installed. Chrome is deb from the official repo and WhatsApp, which I mistakenly believed that is unofficial AppImage, is actually a Chrome App with desktop shortcut running as a separate window.

**Comment by neofight** [comment]
I have the same issue except the application is shown as Slides.

![image](https://user-images.githubusercontent.com/221644/87770579-6328af80-c849-11ea-88af-3cd1e8878670.png)

I installed Chrome using the deb from the official site.

**Comment by stsdc** [comment]
yeah, Chrome needs a special treatment. They doing things in their own way.

**Comment by stsdc** [comment]
@neofight Did You install Slides as a webapp? Or Chrome extension?

**Comment by neofight** [comment]
Neither, it seems to be one of the built in "apps", I've not used it either.
