### ISSUE TITLE
Processes property columns sorting is reversed

### ISSUE THREAD

**Issue by sixpounder** [stsdc/monitor#175]
I don't know if this is intended, but it seems to me that when a column is sorted in ascending order - arrow up - it actually sorts that column in descending order and viceversa
![Screenshot from 2020-04-27 09-24-48](https://user-images.githubusercontent.com/187334/80345170-01b7fc80-8869-11ea-9337-d685c66f78ca.png)

**Comment by ryonakano** [comment]
I can confirm this issue not only in Monitor but also everywhere like FileChooser which allows users sorting columns. So, I think this is not a specific issue neither in Monitor or even elementary OS. Maybe an GTK issue?

**Comment by sixpounder** [comment]
Inspecting it we can see that the image is actually set to the "up arrow" on a descending sort. Is this a GTK default or is it overridden by eOS in some way?
![Screenshot from 2020-04-27 16-25-02](https://user-images.githubusercontent.com/187334/80383511-ef0ee900-88a3-11ea-92d7-42078574dc9f.png)

**Comment by stsdc** [comment]
Probably this: d0a166ba54fcd2bbbbf5be4b5648e26baf483373

**Comment by stsdc** [comment]
Fixed in 808ad7f43d2b7ff652510f238e595b7eab648d59.
