### ISSUE TITLE
Suggestion for AppCenter: Retain previous release descriptions

### ISSUE THREAD

**Issue by cassidyjames** [stsdc/monitor#189]
Thanks for submitting your latest update to AppCenter! While reviewing, we noticed that you've removed previous release descriptions from your AppData. While not currently required, keeping that historical data around is useful. 

We use old release data in AppCenter and on the AppCenter website so users can see how often an app is updated, and to show them the changes between their currently installed version and the latest version. For this to work, apps need to keep at least some historical release data around in the AppData.

Re-adding your previous release descriptions is safe since they're tagged with the version number; AppStream and AppCenter will be able to pair them up correctly just fine.

**Comment by stsdc** [comment]
Fixed in 8be98398aad8d7728d875a8b247603a23484ebbc
