### ISSUE TITLE
Show CPU temperature

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#190]
- [x]  In the System tab
- [x] In the Indicator

**Comment by stsdc** [comment]
New, fresh and juicy issue. Better than #152.

**Comment by dcharles525** [comment]
@stsdc Hey I was doing some research into actually getting the temp straight from the kernel and made a little piece of code in Vala to do so here: https://github.com/dcharles525/Sense.

It supports Intel/AMD (don't have AMD so not 100% it works for those chips)

Hope this helps!

**Comment by stsdc** [comment]
Yes, thanks! I'll check this on my Ryzen.

**Comment by stsdc** [comment]
7c7d4e5
