### ISSUE TITLE
I cant find monitor in Fedora 32

### ISSUE THREAD

**Issue by snowparrot** [stsdc/monitor#200]
Following the instructions in Fedora 32 I get the message that dnf cant find the package...

**Comment by stsdc** [comment]
Looks like a guy who was maintaining Fedora packages no longer does this.

I'm only maintaining for elementary os.

**Comment by stsdc** [comment]
Removed it from readme.

**Comment by stsdc** [comment]
If there will be anyone who will do the packaging, I'll add info about this in the readme.
