### ISSUE TITLE
Support dark theme

### ISSUE THREAD

**Issue by ezeveliz** [stsdc/monitor#201]
With dark theme on, on the system tab the text within de utilization card is white on white.
![Captura realizada el 2020-08-27 13 16 09](https://user-images.githubusercontent.com/24837065/91468236-14b6f980-e868-11ea-9272-b31b9dbdf5ee.png)
black text on white theme
![Captura realizada el 2020-08-27 13 17 06](https://user-images.githubusercontent.com/24837065/91468289-27c9c980-e868-11ea-9937-df095505188f.png)
white text on white background with dark theme

**Comment by stsdc** [comment]
How did You enable dark theme?

**Comment by ezeveliz** [comment]
with tweaks

**Comment by stsdc** [comment]
I'm not supporting dark theme, because it is not official yet. But I'll leave this issue open until that.

**Comment by ezeveliz** [comment]
Ok, thx!

**Comment by DevAlien** [comment]
you can even enabledark theme with the Gtk Inspector. Also the apps must be ready for eOS 6, which supports the dark theme.

**Comment by stsdc** [comment]
In order to build for eOS 6, I have to install it and develop on it. Because a lot of styles changed.
