### ISSUE TITLE
Crashes when opening on elementaryOS 5

### ISSUE THREAD

**Issue by JuanM04** [stsdc/monitor#204]
It crashed instantly with this error after updating to v0.9:

```
TemperatureSensor.vala:77: Failed to open file “/sys/class/hwmon/hwmon0/name”: No such file or directory
```

**Comment by stsdc** [comment]
Could You please `ls /sys/class/hwmon/hwmon0`?

**Comment by JuanM04** [comment]
```
$ ls /sys/class/hwmon/hwmon0
power
device
subsystem
uevent
```

Setup:
* elementaryOS 5.1.7 (based on Ubuntu 18.10)
* Linux 5.4.0-42-generic

**Comment by stsdc** [comment]
What is Your hardware?

**Comment by JuanM04** [comment]
It's a late 2013 iMac

**Comment by stsdc** [comment]
Should be fixed in the next release.
