### ISSUE TITLE
CPU info tooltip cuts off on the left side

### ISSUE THREAD

**Issue by amka** [stsdc/monitor#208]
Better than words
![Monitor 2020-09-14 23-24](https://user-images.githubusercontent.com/519146/93135029-50fcad80-f6e2-11ea-853a-faa76ceef3de.gif)

**Comment by stsdc** [comment]
The whole tooltip needs a design.

**Comment by amka** [comment]
@stsdc well, feel free to close this issue. I'm not bother you to keep it 'till rework.

**Comment by stsdc** [comment]
nah, it's a valid issue. This tooltip needs better layout, because there is even more info in the CPU class itself. If You interested in this, feel free to design a better layout. 

I'm not motivated right now to re-design this by myself 😅, but I'll accept PRs 👍.

**Comment by stsdc** [comment]
Fixed in #278
