### ISSUE TITLE
Elevated permission processes not shown (sudo/root)

### ISSUE THREAD

**Issue by CosCal** [stsdc/monitor#215]
I noticed the "administrator" elevated Files app in elementaryOS (v5.1.7) was not listed in Monitor (v0.9.1) but the non-elevated instance was listed just fine. After verifying with ping in terminal, it appears that elevated processes, via sudo or root, are not shown correctly in Monitor.

When running another instance of Monitor under sudo, the elevated now show, but not the regular processes. I see conversation about a redesign. Was this missing ability just oversight or is there a bug? Thank you for your time.

**Comment by stsdc** [comment]
This is true. Right now Monitor shows only processes of current user. It is not a bug, just not implemented yet. It needs design.
I think it needs some indication that these are root processes.
PRs are welcome.

**Comment by CosCal** [comment]
Personally new to programming, but will research these coveted "Pull Requests" and spread the word.

**Comment by davidak** [comment]
It could be implemented as a settings switch "show all processes" which requests root or sudo password.
