### ISSUE TITLE
Add network up/down in indicator

### ISSUE THREAD

**Issue by yomeuh** [stsdc/monitor#222]
Hi,
And first of all, thanks for the app. It is great.
For my personal usage, as I have sometimes only access to limited bandwith, I'd love to have up/down values in the indicator.
Maybe it could be an option, and the others (cpu, memory, temperature, storage) too ?

**Comment by stsdc** [comment]
Since it will cluttering the Wingpanel with that much info it makes sense to add option to choose what info to display #223
