### ISSUE TITLE
Indicator doesn't update in latest update

### ISSUE THREAD

**Issue by Suzie97** [stsdc/monitor#228]
Hey, I think the new update has broken the wingpanel-indicator. The stats in the indicator don't update anymore.

https://user-images.githubusercontent.com/68198116/115347091-9c25f400-a1ce-11eb-81ee-5c555c9c41bd.mp4

_Originally posted by @Suzie97 in https://github.com/stsdc/monitor/issues/225#issuecomment-823006359_

**Comment by stsdc** [comment]
Please try to restart Wingpanel `killall wingpanel`.

**Comment by Suzie97** [comment]
https://user-images.githubusercontent.com/68198116/115432341-e2f20900-a223-11eb-966d-d7ad0f50412c.mp4

Now the indicator doesn't show up at all. And the notification bell rings.

**Comment by stsdc** [comment]
works for me. Did You try to reinstall?

**Comment by Suzie97** [comment]
I tried reinstalling monitor. Now the indicator doesn't appear. 

I tried it on my other laptop too. The same problem also exists on that computer.

**Comment by stsdc** [comment]
I did just reinstall on my laptop and it still works as expected. This is strange.

**Comment by Suzie97** [comment]
@stsdc Are you using elementary os 6?

**Comment by stsdc** [comment]
I'm using both eos 6 and eos 5.

**Comment by Suzie97** [comment]
It works both on 6 and 5?

**Comment by stsdc** [comment]
Yes. :upside_down_face: 

Try to compile from the source?

**Comment by Suzie97** [comment]
I tried compiling from source, same results☹️

**Comment by stsdc** [comment]
Just released 0.9.4. Should be fixed. Remember to restart wingpanel or reboot.

**Comment by Suzie97** [comment]
Hey, I can't compile from source on the elementary os 6 public beta.

```
rajdeep@HP-1000-Notebook-PC-f4c74608:~/Projects/monitor$ sudo apt install libwingpanel-2.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libwingpanel-2.0-dev
E: Couldn't find any package by glob 'libwingpanel-2.0-dev'
```

How do I install libwingpanel-2.0-dev?? I want to add some actions for the dock and applications menu

**Comment by Suzie97** [comment]
I figured it out. Now it wors.

**Comment by Suzie97** [comment]
The indicator still doesn't work. I tried restarting too.

**Comment by stsdc** [comment]
@Suzie97 did You make `ninja install`?

**Comment by Suzie97** [comment]
Yeah I did, 
![Screenshot from 2021-05-02 21-36-26](https://user-images.githubusercontent.com/68198116/116819697-bd072580-ab8e-11eb-81d2-599cd9b0b51c.png)

Are you aware of these warning?

**Comment by stsdc** [comment]
Did You after `ninja install` restarted Wingpanel? If that not helps then look into  Monitor settings using dconf.

**Comment by Suzie97** [comment]
Now it works.
