### ISSUE TITLE
Build with Wingpanel 3.0

### ISSUE THREAD

**Issue by bobby285271** [stsdc/monitor#233]
https://github.com/elementary/wingpanel/releases/tag/3.0.0

Will be great if the dependencies can be updated so it will be possible to build this with wingpanel 3.0

https://github.com/stsdc/monitor/blob/a649efecfc220c58d0aaf5eea9a6a91203568d20/meson.build#L27

**Comment by stsdc** [comment]
Hello, @bobby285271 !

I'm mograting Monitor to flatpak. And as I understand that right, the Indicator will now be available in flatpak build.

Could you add some sort of a condition, so when building a flatpak package, Indicator will not be built? But still it will build for a Debian package.

**Comment by stsdc** [comment]
Fixed in #240
