### ISSUE TITLE
Failed to read the symbolic link "/proc/1123/fd/0": Permission denied

### ISSUE THREAD

**Issue by davidak** [stsdc/monitor#246]
For some processes, there is a permission error.

>Failed to read the symbolic link "/proc/1123/fd/0": Permission denied

![Screenshot from 2021-09-29 18-10-32](https://user-images.githubusercontent.com/91113/135310902-5a858371-10e7-4325-8001-03672ef2f1cf.png)

the process was started as systemd service with my user:

```
[davidak@gaming:~]$ systemctl status syncthing
● syncthing.service - Syncthing service
     Loaded: loaded (/etc/systemd/system/syncthing.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-09-29 17:49:42 CEST; 45min ago
   Main PID: 1123 (syncthing)
         IP: 1.2M in, 373.6K out
         IO: 25.8M read, 27.9M written
      Tasks: 30 (limit: 38425)
     Memory: 67.4M
        CPU: 6.155s
     CGroup: /system.slice/syncthing.service
             ├─1123 /nix/store/mzf1zy4g8ax5vllhddqg7prrhcxbx4x0-syncthing-1.18.2/bin/syncthing -no-browser -gui-address=127.0.0.1:8384 -home=/home/davidak/.config/syncthing
             └─1257 /nix/store/mzf1zy4g8ax5vllhddqg7prrhcxbx4x0-syncthing-1.18.2/bin/syncthing -no-browser -gui-address=127.0.0.1:8384 -home=/home/davidak/.config/syncthing
```

---

[Nix package](https://nixos.org/), version 0.10.0
NixOS 21.11.git.47bc8a6fda6 (Porcupine)

**Comment by stsdc** [comment]
Where  You able to read this symbolic link manually?

**Comment by davidak** [comment]
No

```
[davidak@gaming:~]$ cat /proc/202034/fd/0
cat: /proc/202034/fd/0: Permission denied

[davidak@gaming:~]$ sudo ls -la /proc/202034/fd/0
lr-x------ 1 davidak syncthing 64 Oct  3 21:47 /proc/202034/fd/0 -> /dev/null
```

**Comment by stsdc** [comment]
Monitor has the same permissions as the user that run it. It will not overcome this.

**Comment by davidak** [comment]
sure. then you should program it differently, so it does not try to do things that will fail. it's not a great user experience when you start a program and it says FAIL

**Comment by stsdc** [comment]
Or maybe You should run it with the right permissions :D

PRs are welcome 😉

**Comment by davidak** [comment]
I just start it from the application menu and expect no errors.

Is this only a problem with NixOS? Do you have similar processes on elementary OS?

**Comment by stsdc** [comment]
Yes. That's why I coded that behavior.

**Comment by davidak** [comment]
>I assume if You'll run with sudo, it will not show this message.

Yes. But it also does not show those processes. Most processes are from root. (known issue https://github.com/stsdc/monitor/issues/215)

![Screenshot from 2021-10-04 16-20-11](https://user-images.githubusercontent.com/91113/135868603-452141e4-0f6c-4be9-9db8-26374381fe17.png)

Also the dark mode of the system is not respected.

I don't think users should run it this way.

A fix could be that there is a button on the right of the error message "allow" which will ask for the sudo or root password.

It's fine when you don't do it yourself and wait for PR. Thanks!

**Comment by stsdc** [comment]
Dark mode is not respected, because dark theme was set for a regular user, not for a root.
