### ISSUE TITLE
Couldn't install `libwingpanel-2.0-dev` with apt-get on Odin. 

### ISSUE THREAD

**Issue by cscottyb** [stsdc/monitor#247]
Couldn't install `libwingpanel-2.0-dev` with apt-get on Elementary OS 6, Odin. Does not exist in Synaptic Package Manager; only `libwingpanel-3.0-dev` was available.

```
E: Unable to locate package libwingpanel-2.0-dev
E: Couldn't find any package by glob 'libwingpanel-2.0-dev'
```

How else can I install libwingpanel-2.0-dev?

**Comment by stsdc** [comment]
Fixed in bcb450163e2c079ccfe680bd963c321564ebcf23. Please use libwingpanel-3.0-dev.
