### ISSUE TITLE
Segmentation fault on virtual machine

### ISSUE THREAD

**Issue by andrewdbate** [stsdc/monitor#281]
After installing on elementary OS 6 from the PPA, the wingpanel disappeared for a few seconds (until it was automatically restarted).

Attempting to open Monitor from the Applications menu did nothing. The icon would appear in the dock and then disappear a few seconds later.

When I attempt to launch from the terminal I get this:
```
$ com.github.stsdc.monitor
Segmentation fault
```

I looked at journalctl and couldn't see anything related to Monitor (not surprising because it appears to seg fault immediately).

The same happens after restarting the computer.

I am happy to provide more info / debug further if you tell me what you need.

Thanks!

**Comment by stsdc** [comment]
Hello, try to run this:  `G_MESSAGES_DEBUG=all GTK_DEBUG=interactive ./com.github.stsdc.monitor`

**Comment by stsdc** [comment]
Also, would help, if You'll try to compile and run `dev` branch. A lot changed.

**Comment by andrewdbate** [comment]
I am actually running elementary OS within a VMware virtual machine. (I use this to test out new software so I don't mess up my local install.) It is VMware workstation 16.2 with workstation 16.2 hardware compatibility with the Debian 11.x 64-bit hardware profile.

I will compile the `dev` branch and report back.

**Comment by andrewdbate** [comment]
I've compiled the `dev` branch and I get a segfault again but slightly different output:
```
$ G_MESSAGES_DEBUG=all GTK_DEBUG=interactive com.github.stsdc.monitor
(com.github.stsdc.monitor:15729): GLib-GIO-DEBUG: 21:22:30.069: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?
(com.github.stsdc.monitor:15729): dconf-DEBUG: 21:22:30.069: watch_fast: "/com/github/stsdc/monitor/settings/" (establishing: 0, active: 0)
(com.github.stsdc.monitor:15729): GLib-DEBUG: 21:22:30.069: unsetenv() is not thread-safe and should not be used after threads are created
(com.github.stsdc.monitor:15729): dconf-DEBUG: 21:22:30.074: watch_established: "/com/github/stsdc/monitor/settings/" (establishing: 1)
(com.github.stsdc.monitor:15729): GLib-GIO-DEBUG: 21:22:30.127: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(com.github.stsdc.monitor:15729): Gtk-DEBUG: 21:22:30.233: Using display (null) for GtkInspector
(com.github.stsdc.monitor:15729): GLib-DEBUG: 21:22:30.744: unsetenv() is not thread-safe and should not be used after threads are created
(com.github.stsdc.monitor:15729): Gtk-DEBUG: 21:22:30.744: Connecting to session manager
** (com.github.stsdc.monitor:15729): DEBUG: 21:22:30.751: HwmonPathsParser.vala:59: Found unknown HWMON Interface: ACAD
** (com.github.stsdc.monitor:15729): DEBUG: 21:22:30.752: CPU.vala:184: Parsed file /usr/share/com.github.stsdc.monitor/database/cpu_features.csv
** (com.github.stsdc.monitor:15729): DEBUG: 21:22:30.752: CPU.vala:184: Parsed file /usr/share/com.github.stsdc.monitor/database/cpu_bugs.csv
** (com.github.stsdc.monitor:15729): DEBUG: 21:22:30.752: CPU.vala:66: Number of cores: 4
Segmentation fault
```

**Comment by stsdc** [comment]
What's output of: `cat /sys/class/hwmon/hwmon*/name` ?

I tested on Fedora 34 using Boxes for Copr last month. A lot of stuff wasn't  working, but definitely no instant segfaults :/

**Comment by andrewdbate** [comment]
Here is the output:
```
$ cat /sys/class/hwmon/hwmon*/name
ACAD
```

**Comment by stsdc** [comment]
Feels like VMware not creating all sysfs entries.
What's output of: `ls /sys/devices/system/cpu` and `ls /sys/devices/system/cpu/cpu`?

**Comment by andrewdbate** [comment]
Here is the output:
```
$ ls /sys/devices/system/cpu
cpu0  cpu1  cpu2  cpu3  cpufreq  cpuidle  hotplug  isolated  kernel_max  modalias  offline  online  possible  power  present  smt  uevent  vulnerabilities
$ ls /sys/devices/system/cpu/cpu
ls: cannot access '/sys/devices/system/cpu/cpu': No such file or directory
```

I also ran this in case it is useful:
```
$ ls /sys/devices/system/cpu/cpu*
/sys/devices/system/cpu/cpu0:
cache  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  power  subsystem  topology  uevent

/sys/devices/system/cpu/cpu1:
cache  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  online  power  subsystem  topology  uevent

/sys/devices/system/cpu/cpu2:
cache  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  online  power  subsystem  topology  uevent

/sys/devices/system/cpu/cpu3:
cache  cpuidle  crash_notes  crash_notes_size  driver  firmware_node  hotplug  node0  online  power  subsystem  topology  uevent

/sys/devices/system/cpu/cpufreq:

/sys/devices/system/cpu/cpuidle:
available_governors  current_driver  current_governor  current_governor_ro
```

**Comment by stsdc** [comment]
heh, tried to reproduce, but can't install elementary because vmware makes 800x600 display and installation app can't fit.

Well, If you're determined enough to run Monitor on VM, I would try to put some debugs here:
https://github.com/stsdc/monitor/blob/9b66526f44e715d0550d6610adbcb2165a063878/src/Resources/CPU.vala#L66-L69

Also You may try to use gdb: 

> Run gdb /path/to/monitor in your terminal. Type run and then press Enter to run an app. If we get a segfault type bt and press Enter to see a backtrace.

**Comment by andrewdbate** [comment]
To fix the problem with the installation screen, you need to go into the VM settings and use UEFI instead of BIOS and then the installation screen will fit without problems.

**Comment by stsdc** [comment]
Managed to install. Will investigate when in a spare time.
