### ISSUE TITLE
possible to make wingpanel optional?

### ISSUE THREAD

**Issue by SwampRabbit** [stsdc/monitor#284]
Hello, I'm a package maintainer for MX Linux, I've been wanting to bring monitor to our repos for awhile now.
I never really tried after I saw the hard dependency on wingpanel, but finally got around to messing with it.

I am able to simply patch out the portions in meson.build which require wingpanel via a debian/patch and have the build complete.
It seems to still work really really nicely in Xfce in the limited testing that I have done.
I plan to push it to our Test Repo soon for wider user testing.

I saw the mentions about issues with wingpanel and updated flatpak builds, so I assume my request is similar in nature, and may already be in the chute for changing.

If its not being worked already, how hard would it be to make the wingpanel build and runtime depends optional?

Thanks for your consideration.

**Comment by SwampRabbit** [comment]
@stsdc awesome, thank you for the fast response.  I'll do a build off of dev branch soon, wasn't sure how fluid that was at the time.

I'm no expert on indicators, you could do native ones for each DE, but that may become a nightmare long term.
Some of the older indicator standards and application backends are kinda dead.  Indicators can still be a pain for sure.

I have noticed many are using https://github.com/AyatanaIndicators which has gained a lot of traction and is being used by a lot of Distros and applications now by default.

I'm not sure how Linux Mint is doing indicators now, maybe using the cross platform xapp stuff, but their applications have good solid and usable indicators across DEs.  If AyatanaIndicators doesn't look like it might work, I'd look at how Linux Mint handles theirs, they always do great and smart stuff.

**Comment by stsdc** [comment]
@SwampRabbit please check `meson-refactor` branch. Indicator will not  be built and dependency should not be required.

**Comment by SwampRabbit** [comment]
@stsdc thanks!  I saw the commits, I'll be building off that as soon as I get some other packages out of the way.  Thanks again

**Comment by stsdc** [comment]
@SwampRabbit  merged to dev. Will close this issue. Feel free to report any issues.

**Comment by SwampRabbit** [comment]
@stsdc sorry for the delay and not really related to the initial issues, but....

Hit a snag trying to build off of the merged dev now in a schroot because of that meson subproject for live-chart requiring GitHub access during the build.

Took the opportunity to do the Debian packaging for live-chart, which is here for now https://github.com/SwampRabbit/live-chart , it builds finally after cutting out the tests which also won't work in a schroot, I just haven't tested the built .debs yet.

**Comment by stsdc** [comment]
It shouldn't require access, strange. 

Also must inform You that I found earlier today an issue with building a project.

 I moved a list of source files and an `executable(...)` to a meson.build file that's in `./src` and made a `subdir('src')` in a root meson file. But it is not running the executable () function :/ and is not compiling it. But it will show an error in it if something is wrong.

Looks like previously it run the cached binary 😑

**Comment by stsdc** [comment]
@SwampRabbit can confirm, that everything installs as it should on `dev` branch. You may test. If You'll find anything let me know.

Regarding live-chart, I was able succesfully build Monitor on Copr and Launchpad, no special Github access was needed, so :man_shrugging:

**Comment by SwampRabbit** [comment]
@stsdc so silly me, somehow had empty subprojects folders when I downloaded the dev branch last time

getting past the previous build issues, but it seems to start to die at [131/196] with a bunch of "error: syntax error"....

my brain is toast for the day, I can start a new Issue if you'd like for the above if I can't work through it

For what it's worth, I'm building on Debian 11 Bullseye in a pbuilder schroot, the 0.11.0 release built great and worked great.

**Comment by stsdc** [comment]
yeah, gotta remember to clone with a recursive flag.

Please write a new issue with logs, I'll look into it, why it's not building.
