### ISSUE TITLE
Segmentation fault on Elementary os 6.1

### ISSUE THREAD

**Issue by zin07** [stsdc/monitor#290]
Hi, 

I get this when I try to run:

ibm@ThinkPadX240:~$ G_MESSAGES_DEBUG=all GTK_DEBUG=interactive com.github.stsdc.monitor
(com.github.stsdc.monitor:1890): GLib-GIO-DEBUG: 16:59:06.757: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?
(com.github.stsdc.monitor:1890): dconf-DEBUG: 16:59:06.758: watch_fast: "/com/github/stsdc/monitor/settings/" (establishing: 0, active: 0)
(com.github.stsdc.monitor:1890): GLib-DEBUG: 16:59:06.758: unsetenv() is not thread-safe and should not be used after threads are created
(com.github.stsdc.monitor:1890): dconf-DEBUG: 16:59:06.759: watch_established: "/com/github/stsdc/monitor/settings/" (establishing: 1)
(com.github.stsdc.monitor:1890): GLib-GIO-DEBUG: 16:59:06.768: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(com.github.stsdc.monitor:1890): Gtk-DEBUG: 16:59:06.819: Using display (null) for GtkInspector
(com.github.stsdc.monitor:1890): GLib-DEBUG: 16:59:07.205: unsetenv() is not thread-safe and should not be used after threads are created
(com.github.stsdc.monitor:1890): Gtk-DEBUG: 16:59:07.205: Connecting to session manager
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.235: CPU.vala:51: Number of cores: 4
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.235: TemperatureSensor.vala:41: Found temp. sensor: coretemp
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.236: TemperatureSensor.vala:63: 35000
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.236: TemperatureSensor.vala:63: 35000
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.236: TemperatureSensor.vala:80: Found temp. sensor: BAT1
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.236: TemperatureSensor.vala:80: Found temp. sensor: AC
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.236: TemperatureSensor.vala:80: Found temp. sensor: thinkpad
** (com.github.stsdc.monitor:1890): DEBUG: 16:59:07.236: TemperatureSensor.vala:80: Found temp. sensor: acpitz
Segmentation fault

**Comment by stsdc** [comment]
Hello @zin07, please describe Your hardware configuration. Are You using LUKS?

**Comment by zin07** [comment]
Hi, 

It is a standard EOS 6.1 install (only swap is encrypted).

Regards
Zdravko

**Comment by zin07** [comment]
I have disabled encryption  but still the same result.

**Comment by stsdc** [comment]
There was this issue https://github.com/stsdc/monitor/issues/281, it was, because of empty drive id of lvm, which was fixed in https://github.com/stsdc/monitor/commit/a6bc431afcd297e08610581dd861de10499afde7

You may try to build dev branch and check if problem persists or wait a few days. I'll release a new version soon.

**Comment by stsdc** [comment]
@zin07 Do You still experience this issue with a new release?

**Comment by zin07** [comment]
Hi, No just tried and the app works! Thanks!!!On Fri, Jan 14, 2022 at 8:11 PM, Stanisław ***@***.***> wrote:
@zin07 Do You still experience this issue with a new release?

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/stsdc/monitor/issues/290#issuecomment-1013442174",
"url": "https://github.com/stsdc/monitor/issues/290#issuecomment-1013442174",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
