### ISSUE TITLE
Monitor does not always remember indicator preferences after close

### ISSUE THREAD

**Issue by andrewdbate** [stsdc/monitor#302]
Sometimes when Monitor is quit and relaunched, it does not remember the indicator preferences.

I choose to use the wingpanel indicator with only the CPU and memory percentages shown (and not the temperate or network stats). However, sometimes when I quit monitor and open it again, it will show the CPU, memory _and_ temperature in the wingpanel indicator (which is the default configuration). Monitor forgets the preferences that were set when it quit (or perhaps the preferences get overwritten with the default configuration when it launches again?).

I show this in the following video (12 seconds):

https://user-images.githubusercontent.com/2998569/151883099-4af1d4d3-50d0-4041-ba8e-023d9d3ff399.mp4

In the video:

1. Monitor is initially not open
2. I launch Monitor (from the terminal, just so you can see the version and when it terminates)
3. I then quit Monitor
4. I then relaunch Monitor. But then the indicator preferences have been forgotten because it now shows the temperate (which was not enabled before).

This does not happen every time, but happens about 40% of the time for me. Sometimes the preferences are remembered when Monitor is quit and opened again.

Note: In the video, please ignore that the memory percentage is momentarily shown as -2147483648% because that has been reported separately as https://github.com/stsdc/monitor/issues/296.

**Comment by stsdc** [comment]
That's strange, can't reproduce it :(

**Comment by andrewdbate** [comment]
It doesn't happen to me every single time. I just "got lucky" when I recorded the video that it happened the first time, but I would expect it would happen at least 1 time out of 5.

I have just tried to reproduce it again locally, and I have found that you need to have the "start in background" option turned on as shown below:
![Screenshot from 2022-02-18 00 46 41](https://user-images.githubusercontent.com/2998569/154596145-a392bce3-84a4-480a-b855-786bedbcbece.png)

If I disable "start in background" then the issue doesn't seem to happen.

**Comment by stsdc** [comment]
@andrewdbate yep, I can confirm now
