### ISSUE TITLE
2373 segmentation fault com.github.stsdc.monitor

### ISSUE THREAD

**Issue by pauloricardosb** [stsdc/monitor#305]
I installed the program through the ppa available for version 6.1 of elementary os. When accessing the application from the application menu, it simply does not open (there is no change on the desktop or indication that the program is starting). 

Finally, when accessing through the terminal, I only get the following message:

<img src="https://i.pinimg.com/originals/74/8d/45/748d4531f7e050901c9ba98acc3bb895.jpg"> <br>

What could be happening? :/

**Comment by stsdc** [comment]
Hello,

try to run it like this: `G_MESSAGES_DEBUG=all GTK_DEBUG=interactive com.github.stsdc.monitor` and also you may try to run gdb: 

Run gdb /path/to/monitor in your terminal. Type run and then press Enter to run an app. When we get a segfault type bt and press Enter to see a backtrace.

**Comment by pauloricardosb** [comment]
Hey! :) 

Well, here are the screenshots with the results of the following commands.

`1. G_MESSAGES_DEBUG=all GTK_DEBUG=interactive com.github.stsdc.monitor
`

The end result was this:

`[2]    7839 segmentation fault  G_MESSAGES_DEBUG=all GTK_DEBUG=interactive com.github.stsdc.monitor
`

[Complete output here](https://drive.google.com/file/d/1aWNU0BZz47V9SYIF40t8qkkvLN-5NeQH/view?usp=sharing)


`2. gdb /path/to/monitor`

<img src="https://i.pinimg.com/originals/fc/7b/33/fc7b3391be863b48fce7ceefade22de6.jpg" width="400px">

`3. run`

<img src="https://i.pinimg.com/originals/27/3f/d2/273fd22067e17dcb7703b291b89a524d.jpg" width="400px">

`4. bt`

<img src="https://i.pinimg.com/originals/26/23/f4/2623f494e99f66dc0a260f739b473b7a.jpg" width="400px">

**Comment by stsdc** [comment]
Welp, that's strange. You must have specific hardware configuration, that is not supported.

You might try to build Monitor from sources and poke there. :grimacing:

**Comment by pauloricardosb** [comment]
Alright! Thank you ❤🥲

**Comment by stsdc** [comment]
Out of curiosity, what hardware are you using? What Linux kernel? Are You using elementary os?

**Comment by stsdc** [comment]
@pauloricardosb might be connected to #294
