### ISSUE TITLE
Feature request: Sort list of opened files for easier reading

### ISSUE THREAD

**Issue by andrewdbate** [stsdc/monitor#317]
Monitor shows the list of opened files for each process. This is very useful but sometimes the list is long.

It would therefore be helpful if the list of opened files was always shown in sorted order so that you can more quickly make sense of the list.

This screenshot shows that files are not always in sorted order:
![monitor-opened-files](https://user-images.githubusercontent.com/2998569/173207915-4dc59c90-ef1d-4244-9307-2d93fe31022b.png)

The sorting algorithm used should definitely be worst-case optimal, i.e. O(n log n), otherwise the performance could be slow on long lists of opened files.

Thanks!

**Comment by stsdc** [comment]
Sorting provided by TreeView:
![obraz](https://user-images.githubusercontent.com/6031763/173245654-a842886c-e03a-4bb4-bcbd-94dff2bbf6b5.png)

**Comment by andrewdbate** [comment]
This looks good to me!
