### ISSUE TITLE
Add repo for Fedora 36

### ISSUE THREAD

**Issue by amminadabz** [stsdc/monitor#324]
Fedora 36 is out, as well as the accompanying version of Ultramarine Pantheon. Monitor should be installable for those of us running Pantheon on a Fedora base.

**Comment by stsdc** [comment]
Added: https://copr.fedorainfracloud.org/coprs/stsdc/monitor/

But please note, that I have been struggling recently to package for Fedora 35 and did not packaged the most recent version of  Monitor. Things just break constantly and I need someone to help me with this, since I do not have enough time take care of this myself.

**Comment by amminadabz** [comment]
Thank you, and I understand. I hope that someday I can learn enough programming to contribute to projects like this, but with college and everything else I don't have time to get much further than my two classes in C++.

Not working yet, will try again in a few hours:
`$ sudo dnf install com.github.stsdc.monitor
Copr repo for monitor owned by stsdc                       500  B/s | 257  B     00:00    
No match for argument: com.github.stsdc.monitor
Error: Unable to find a match: com.github.stsdc.monitor
[evanmobley@onix ~]$ dnf search stsdc
Copr repo for monitor owned by stsdc                       517  B/s | 257  B     00:00    
No matches found.
`

**Comment by stsdc** [comment]
That's because a package wasn't published somehow.  If I'll have some time I'll look into it in this week.

**Comment by stsdc** [comment]
Hi, it looks like newer Fedora releases doesn't have some necessary packages to compile Monitor. Therefore it will not be possible to publish it on COPR :(
