### ISSUE TITLE
Feature request: Option for refresh interval

### ISSUE THREAD

**Issue by iblazhko** [stsdc/monitor#325]
Please consider an option to set refresh interval.

From what I can see it is currently hardcoded to 2sec,  but it may be useful to add an option to tune this setting.

The reason I am proposing this is that the Monitor is the most CPU-consuming process when machine is idling.

![stsdc-monitor](https://user-images.githubusercontent.com/87576/187188859-1261f18d-1853-40ac-8edd-c3a2f2aa4d09.png)

Maybe dropping refresh rate to 3-5sec would help.

* * * 
Monitor 0.14.0 on elementaryOS 6.1

**Comment by stsdc** [comment]
Fixed in #334
