### ISSUE TITLE
Wrong cpu frequency indication

### ISSUE THREAD

**Issue by adm313** [stsdc/monitor#336]
Hi
I've noticed an issue with the cpu frequency indication... at least in Ubuntu and with my cpu (3.3 is the Turbo max speed not the current one).
I''l look into it to try to find the reason...

![image](https://user-images.githubusercontent.com/105816964/201609265-06badbc3-1216-495d-9013-7719c75a65f4.png)

**Comment by stsdc** [comment]
Check here: https://github.com/stsdc/monitor/blob/50c5101b1204dd09b12f2ca850d6ac28a11c4962/src/Resources/CPU.vala#L129-L150

Also on what distro are you running? Because I noticed that some icons are missing and stylesheet is different 🤨

**Comment by adm313** [comment]
Ubuntu 22.10

**Comment by adm313** [comment]
This one should work better: it calculates the harmonic mean.. it is less prone to increase the value in only few cores are topping and the most are sleeping.


    // From https://github.com/PlugaruT/wingpanel-monitor/blob/edcfea6a31f794aa44da6d8b997378ea1a8d8fa3/src/Services/Cpu.vala#L61-L85
    private void update_frequency () {
        double inverse_sum = 0;
        double freq_value = 0 ;

        core_total_number = (int) get_num_processors ();

        for (uint cpu_id = 0; cpu_id < core_total_number; ++cpu_id) {
            string cur_content;
            try {
                FileUtils.get_contents ("/sys/devices/system/cpu/cpu%u/cpufreq/scaling_cur_freq".printf (cpu_id), out cur_content);
            } catch (Error e) {
                warning (e.message);
                cur_content = "0";
            }
            freq_value = double.parse (cur_content);
            inverse_sum += 1 / freq_value;
        }
        _frequency = (double) core_total_number/inverse_sum ;
    }

**Comment by adm313** [comment]
When it comes to the lack of some characters: this is what I see in Visual Studio.
It's a Unicode issue I guess. The same happens in other labels.

![image](https://user-images.githubusercontent.com/105816964/201758126-e839ef1b-db73-4b2a-8dd1-4f3fc58af5b6.png)

**Comment by stsdc** [comment]
I'll take look into this.

About characters, I'm using some unicode characters / emoji. I suppose there are no extended fonts installed. :thinking:
