### ISSUE TITLE
Could not install from ppa on Elementary OS 7

### ISSUE THREAD

**Issue by arch3rtemp** [stsdc/monitor#346]
Hello
I followed the instructions in readme file but to no avail. It says it cannot find the ppa
Elementary OS 7, Linux 5.19.0-32-generic

> archil@Archil-Laptop:~/Downloads/monitor/builddir$ sudo add-apt-repository ppa:stsdc/monitor
Repository: 'deb https://ppa.launchpadcontent.net/stsdc/monitor/ubuntu/ jammy main'
Description:
This repository contains Monitor package.
Drop a star: https://github.com/stsdc/monitor
Toss a coin: https://www.paypal.me/stsdc
More info: https://launchpad.net/~stsdc/+archive/ubuntu/monitor
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/stsdc-ubuntu-monitor-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/stsdc-ubuntu-monitor-jammy.list
Adding key to /etc/apt/trusted.gpg.d/stsdc-ubuntu-monitor.gpg with fingerprint 4B64522D1CF6294C62CBEE5D4CC7D5561DCC5602
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://mirrors.ubuntu.com/mirrors.txt Mirrorlist [64 B]                                                     
Hit:5 https://ppa.launchpadcontent.net/elementary-os/stable/ubuntu jammy InRelease                                
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease                                                                                          
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                         
Get:6 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [13.1 kB]                              
Hit:7 https://ppa.launchpadcontent.net/elementary-os/os-patches/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [853 kB]   
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [164 kB]     
Ign:8 http://ubuntu.grena.ge/ubuntu jammy-updates/universe Sources                  
Ign:9 http://ubuntu.grena.ge/ubuntu jammy-updates/main Sources                      
Ign:10 http://ubuntu.grena.ge/ubuntu jammy-updates/main amd64 Packages              
Ign:14 https://ppa.launchpadcontent.net/stsdc/monitor/ubuntu jammy InRelease        
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [17.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/universe Sources [199 kB]                                                    
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main Sources [354 kB]               
Err:15 https://ppa.launchpadcontent.net/stsdc/monitor/ubuntu jammy Release                                     
  404  Not Found [IP: 185.125.190.52 443]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [897 kB]       
Reading package lists... Done                            
E: The repository 'https://ppa.launchpadcontent.net/stsdc/monitor/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
archil@Archil-Laptop:~/Downloads/monitor/builddir$ sudo apt install com.github.stsdc.monitor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package com.github.stsdc.monitor
E: Couldn't find any package by glob 'com.github.stsdc.monitor'

**Comment by stsdc** [comment]
Hello @arch3rtemp!
What version of elementary are you using?

**Comment by arch3rtemp** [comment]
@stsdc elementary OS 7 Horus, kernel = Linux 5.19.0-32-generic

**Comment by arch3rtemp** [comment]
I think that is the crucial part
`Err:8 https://ppa.launchpadcontent.net/stsdc/monitor/ubuntu jammy Release                                                                                   
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done                                                                                                                               
E: The repository 'https://ppa.launchpadcontent.net/stsdc/monitor/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by stsdc** [comment]
I didn't make a release for Horus yet.

**Comment by arch3rtemp** [comment]
Ok. Waiting for the release. 
By the way I have compiled manually the source code and it works on Horus

**Comment by stsdc** [comment]
Glad to hear that, I'll try to find a bit of time to make the release.

**Comment by stsdc** [comment]
@arch3rtemp released a new version. Now it should be possible to install on Horus :+1:
