### ISSUE TITLE
Packaging broken on Fedora?

### ISSUE THREAD

**Issue by electricduck** [stsdc/monitor#348]
There seems to be an incosistency with the version on Fedora (using the [Copr repository](https://copr.fedorainfracloud.org/coprs/stsdc/monitor/monitor/)). On my install, Monitor reports its **0.12.0** and `rpm` reports it to be **0.15.1**. Either:
 * Something weird happens on Fedora and Monitor reports the wrong version
 * Packaging is broken on the Copr repo and its now erroneously building **0.12.0**
   * Did notice a build failure on **0.15.1** ([build 5451084](https://copr.fedorainfracloud.org/coprs/stsdc/monitor/build/5451084/)), but even then the version before that is **0.13.0**

I'm assuming the install of Monitor is genuinely at **0.12.0** from Copr now, as the reference to the 🕊️ Ukranian war is missing in the status bar (and, as far as I can see, that hasn't been removed), and something has happened to cause it to downgrade the version during the build.

### Screenshot of Monitor (showing 0.12.0)

![image](https://user-images.githubusercontent.com/1594644/220516101-0fa32b97-9866-4a56-9626-a94afd2acc8c.png)

### Output from `com.github.stsdc.monitor` (showing 0.12.0)

```
ducky@tanager:~$ com.github.stsdc.monitor --help

 Monitor 0.12.0 

Usage:
  com.github.stsdc.monitor [OPTION…]

Help Options:
  -h, --help                    Show help options

Application Options:
  -b, --start-in-background     Start in background with wingpanel indicator
```

### Output from `rpm` (showing 0.15.1)

```
ducky@tanager:~$ rpm -qi com.github.stsdc.monitor
Name        : com.github.stsdc.monitor
Version     : 0.15.1
Release     : 1.fc36
Architecture: x86_64
Install Date: Wed 22 Feb 2023 01:39:10 GMT
Group       : Unspecified
Size        : 1147226
License     : GPLv3
Signature   : RSA/SHA256, Sat 04 Feb 2023 16:52:02 GMT, Key ID b44e4a74ae8afc6e
Source RPM  : com.github.stsdc.monitor-0.15.1-1.fc36.src.rpm
Build Date  : Sat 04 Feb 2023 16:51:12 GMT
Build Host  : copr-hv-x86-64-03-prod-00767067-20230204-151342
Vendor      : Fedora Copr - user stsdc
URL         : https://github.com/stsdc/monitor
Summary     : Manage processes and monitor system resources
Description :
```

**Comment by stsdc** [comment]
![image](https://user-images.githubusercontent.com/6031763/220700253-19c846b5-584c-42b5-8d4d-1a4f76de41bf.png)

For Fedora 37 there is no wingpanel dependency ton which Monitor relies.

**Comment by stsdc** [comment]
Copr has an old archive, but a new spec file.

**Comment by electricduck** [comment]
> For Fedora 36 [it shows](https://download.copr.fedorainfracloud.org/results/stsdc/monitor/fedora-36-x86_64/05451084-com.github.stsdc.monitor/builder-live.log.gz) that it is building 0.12

Hm, interesting, I definitely did used to have a newer version on Fedora.

> For Fedora 37 there is no wingpanel dependency on which Monitor relies.

Just to keep you up-to-date about the 37 situation, Pantheon is missing from official Fedora repos for the forseeable due to complications with things it relies on, so there's little point in building on 37.

**Comment by stsdc** [comment]
@electricduck  please check new release.

**Comment by electricduck** [comment]
> @electricduck please check new release.

Yep, back on 0.16.0 on Fedora!
