### ISSUE TITLE
Settings schema 'com.github.stsdc.monitor.settings' does not contain a key named 'containers-view-state'

### ISSUE THREAD

**Issue by adm313** [stsdc/monitor#354]
Hi 
today I've downloaded the latest version of the monitor,. compiled it and run and this is what I got
![image](https://user-images.githubusercontent.com/105816964/231742565-bdfcb49b-3a27-49d5-9650-b1027fbd76b6.png)
I've tried adding the entry to the schema but keeps on complaining.
![image](https://user-images.githubusercontent.com/105816964/231742842-2a9fb9b9-f3a0-4b6f-8a7f-9ced65356bac.png)

Am I doing something weird?

BR
Andrea

**Comment by stsdc** [comment]
Hi, the entry is already there.  Did you run `ninja install` ?

**Comment by adm313** [comment]
Hi 
yes I did it
![image](https://user-images.githubusercontent.com/105816964/232024672-bd244f17-ffe8-4a1f-a078-a35f025764d5.png)
Just to double check...
![image](https://user-images.githubusercontent.com/105816964/232025093-3862db2d-1930-4f9a-92c3-0b1a97171e1d.png)
The weirdest thing is that .... the reference is there in the xml schema
![image](https://user-images.githubusercontent.com/105816964/232025659-47d83d00-739d-4756-8c94-bc160708b2cc.png)
but it is not there looking at dconf-editor
![image](https://user-images.githubusercontent.com/105816964/232025839-cb4a9222-9aa5-42f8-a299-6a10911f9772.png)

**Comment by adm313** [comment]
Fixed...
I had to manually remove the compiled schemas from /usr/local/share/glib-2.0/schemas/ ....
I don't know why they were there too.

Done
Thanks
Andrea
