### ISSUE TITLE
Process Name: "Game 460807638964371468"

### ISSUE THREAD

**Issue by davidak** [stsdc/monitor#357]
![Screenshot from 2023-05-24 18-28-40](https://github.com/stsdc/monitor/assets/91113/26d9beb5-0a10-4c92-9a3c-b3fbc3c0c658)

Where did it get that name from? It seem wrong.

The Process:

```
$ ps auxf
...
davidak     3571  1.6  0.7 782160 55384 ?        Rl   17:48   0:48 io.elementary.terminal
davidak     3603  0.0  0.0 227104  7492 pts/0    Ss   17:48   0:00  \_ /run/current-system/sw/bin/bash
davidak     3756  0.7  0.6 879348 50176 pts/0    Sl+  17:51   0:21  |   \_ /nix/store/f5388qkbswkv8g8aan1vjy825ij3myrc-eog-44.1/bin/eog
```

Command:

`nix run nixpkgs#gnome.eog`

Expected Name:

The program is called "Image Viewer" (eog).

Version:

monitor-0.14.0

**Comment by stsdc** [comment]
[Glib.AppInfo](https://valadoc.org/gio-2.0/GLib.AppInfo.html) is used to obtain name and icon.

Getting a list of apps:
https://github.com/stsdc/monitor/blob/4a555e384ee808a2b50060fe14d829694c563566/src/Managers/ProcessManager.vala#L36-L58

then trying to match with processes:
https://github.com/stsdc/monitor/blob/4a555e384ee808a2b50060fe14d829694c563566/src/Managers/ProcessManager.vala#L202-L216

**Comment by stsdc** [comment]
Hi @davidak I have rewrote the process to app matching logic. May I ask you to test this PR? Try to open apps and check if the icons and names correspond to the process (you may hover a cursor over app name on the sidebar to see process command).
