### ISSUE TITLE
AMDGPU VRAM usage wrong

### ISSUE THREAD

**Issue by davidak** [stsdc/monitor#369]
Monitor shows VRAM is 1%, while all other tools* say it's 80%.

![Screenshot from 2024-02-25 22 10 28](https://github.com/stsdc/monitor/assets/91113/4a57ea1e-20f3-4bf6-bc19-f0c0369e913f)

* tested with radeontop, amdgpu_top, nvtop, radeon-profile (AMDs own tool)

---

NixOS 23.11.4703.c5101e457206
monitor-0.17.0

**Comment by stsdc** [comment]
The VRAM value is taken from here:
https://github.com/stsdc/monitor/blob/002146e81985d307add585fb63f80aaecd344b4c/src/Resources/GPU/GPUAmd.vala#L28-L30

Described here: https://www.kernel.org/doc/html/v5.13/gpu/amdgpu.html#busy-percent
I thought I could trust sysfs :(

**Comment by davidak** [comment]
That seem like what we want. Maybe it's a bug in the API.

But i would also like to be able to see how much VRAM is used (helps with debugging), so to solve both, you could use these values and calculate the usage percent yourself.

```
[root@gaming:~]# cat /sys/class/drm/card0/device/mem_info_vram_used
6812925952

[root@gaming:~]# cat /sys/class/drm/card0/device/mem_info_vram_total
8573157376
```

**Comment by stsdc** [comment]
@davidak Please check
