### ISSUE TITLE
Statusbar overhaul idea

### ISSUE THREAD

**Issue by ovdeathiam** [stsdc/monitor#37]
This is a feature request.

I think that statusbar could give a litle more info in first glance if used with some diagrams like those gnome system monitor uses. Please see the picture attached. The information it could show is:

- CPU usage (not necessarily per core) with maybe total process count
- MEM usage (RAM)
- SWAP usage (not sure if you could combine it with MEM)

![draft1](https://user-images.githubusercontent.com/946846/31718916-e353777a-b411-11e7-9b22-27c94952d04c.png)

**Comment by stsdc** [comment]
Thank You for this mockup.
Yes, I'm planning to make statusbar more informative until version 1.0

If You have another ideas feel free to post them here or open a new issues.

**Comment by ovdeathiam** [comment]
Since you are not dismissing the idea I'm adding two more polished versions of that mockup.
![draft2](https://user-images.githubusercontent.com/946846/31764254-eb13a228-b4c0-11e7-87f8-110fc40b5cf6.png)
![draft2](https://user-images.githubusercontent.com/946846/31765421-993b3f8e-b4c4-11e7-9bb2-cef9b1dbe270.png)


It all depends on what kind of graphs/widgets you'll be able to use there. CPU might use a graph, but MEMORY/SWAP imo only needs a static representation. If possible it might be good to highlight the portion of memory used by selected process etc.
