### ISSUE TITLE
Show memory usage in bytes

### ISSUE THREAD

**Issue by giovannicaligaris** [stsdc/monitor#38]
It would be ideal if we can have an option to see the memory in bytes. 

As for example 

![screenshot from 2017-10-18 22 38 10](https://user-images.githubusercontent.com/26255347/31744006-0eee2ee6-b455-11e7-8f89-f11aa976ba4a.png)

**Comment by stsdc** [comment]
@giovannicaligaris 
![obraz](https://user-images.githubusercontent.com/6031763/39646060-847e9d3c-4fda-11e8-9f09-25fbc8f17e55.png)
