### ISSUE TITLE
Process tree (main view): if icon missing for the process, icon is taken from previous process

### ISSUE THREAD

**Issue by tpalucki** [stsdc/monitor#47]
In the tree view of the process, when process icon is missing, icon is loaded from previous item from the list. Please consider attached graphics. Problematic process here is Intellij IDEA which has other program icon loaded or the default on after clicking on the previous item.
![icon_problem_1](https://user-images.githubusercontent.com/2963128/36198108-f3940fca-1175-11e8-966a-4591b951d506.png)
Default icon:
![icon_proglem_2](https://user-images.githubusercontent.com/2963128/36198140-0d77ac94-1176-11e8-863d-07849530e693.png)

**Comment by stsdc** [comment]
throws same error for PyCharm snap:
`file /build/com.github.stsdc.monitor-0.3.5/src/Widgets/OverallView.vala: line 83: uncaught error: Failed to open file 'file:///snap/pycharm-professional/66/bin/pycharm.png': Nie ma takiego pliku ani katalogu (g-file-error-quark, 4)`
