### ISSUE TITLE
Design an indicator icons

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#49]
- [x]  CPU icon
- [x] Memory (RAM) icon
- [x] Temperature #203 

Icons must be consistent with other elementary native indicator icons.

**Comment by libredeb** [comment]
You need help to design that icons? can try to make some and you decide if they are useful or not

**Comment by dveezhok** [comment]
https://yadi.sk/d/fxNvJeiH3a8Ake — icons

**Comment by stsdc** [comment]
@libredeb that would be nice. The main constrain here is that they must consistent with other eOS indicator icons.

**Comment by dveezhok** [comment]
@stsdc, my icons is not consistent?

**Comment by stsdc** [comment]
@dveezhok They are nice, but You must remember that indicator icons have 16px size, so You can't add much details to icon. The closest icons I found that I like are [here](https://www.flaticon.com/packs/it-components-2). Hovewer they need to be redesigned for 16px size.

**Comment by dveezhok** [comment]
@stsdc, redesigned 16px from 'here'
https://yadi.sk/d/e4XPnsin3a8rdg

**Comment by micahilbery** [comment]
I can't remember why but I made some icons that would work for this awhile ago.
Thoughts?

![demo](https://user-images.githubusercontent.com/10608836/43998041-d08d7c1e-9db1-11e8-94d3-7b1b5badd9ff.png)

**Comment by lainsce** [comment]
I could try making some. But I like @micahilbery 's attempt :+1:

**Comment by stsdc** [comment]
@lainsce yes, they're great, but too much details. elementary indicator icons don't have this much details

**Comment by stsdc** [comment]
@lainsce would be awesome!

**Comment by stsdc** [comment]
Draw some icons: 1f4fe1e31f33139da29d0baa312908ee604da8e6

Ended up with @micahilbery style :stuck_out_tongue: : 
![obraz](https://user-images.githubusercontent.com/6031763/52541051-21acee80-2d91-11e9-9301-1a710bf0b31b.png)
