### ISSUE TITLE
Show memory usage in GiB

### ISSUE THREAD

**Issue by uncertainquark** [stsdc/monitor#50]
Show memory usage in the status bar in GiB and not just %, i.e. 2 GiB/ 4 GiB. It gives more information.
![screenshot from 2018-05-03 14-21-12](https://user-images.githubusercontent.com/22585732/39567630-46014b5c-4edd-11e8-84a2-2a68e274428b.png)

**Comment by stsdc** [comment]
Duplicate of #38
