### ISSUE TITLE
Show swap usage in the status bar

### ISSUE THREAD

**Issue by uncertainquark** [stsdc/monitor#51]
Show 'swap' usage alongside CPU and memory in the status bar. Both GNOME System Monitor and KDE SysGuard show it.
![screenshot from 2018-05-03 14-21-12](https://user-images.githubusercontent.com/22585732/39568079-af095b02-4ede-11e8-95aa-b7e82c705ead.png)

**Comment by ryonakano** [comment]
Hi, I've worked on this (see #115) and I want some design help. Showing swap usage is possible and the UI looks like this:

![2019-10-13 09 46 26 の画面録画](https://user-images.githubusercontent.com/26003928/66709397-5a78e980-ed9e-11e9-8811-e67b5cefcaea.gif)

Actually, however, the icon for the swap is the same as the one for the memory at the moment. Would someone create a new icon for the swap usage?
