### ISSUE TITLE
Make the status bar text bold

### ISSUE THREAD

**Issue by uncertainquark** [stsdc/monitor#52]
It might be a nice idea to make the status bar text "CPU" and "Memory" bold for grabbing attention to the important bits. 
![screenshot from 2018-05-03 14-21-12](https://user-images.githubusercontent.com/22585732/39568221-17131b8e-4edf-11e8-8231-7d4b14f9c892.png)

**Comment by dveezhok** [comment]
... or just a little more font size for status bar. Bold - is no good choice.
