### ISSUE TITLE
After some time hangs on

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#54]
Loops indefinitely with this:

    [DEBUG 02:44:15.571042] GenericModel.vala:226: add_process_to_row 0
    [WARNING 02:44:15.571162] Process.vala:129: File '/proc/0/cmdline' doesn't exist.

**Comment by stsdc** [comment]
Looks like there is problem when retrieving PID from window. When opening Steam it shows PID 0.
https://github.com/stsdc/monitor/blob/616aa77d5fbb4845cea220d6b2044263a9d4070b/src/Managers/AppManager.vala#L47-L66

**Comment by giovannicaligaris** [comment]
I am having the same issue on Juno

**Comment by stsdc** [comment]
The error persist, but can You confirm that it still crashes the app?
