### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [stsdc/monitor#55]
Arch Linux Support

I will support your application in Arch Linux.

Please add a section containing the following instruction:

## Arch Linux
Arch Linux users can find Monitor under the name [pantheon-system-monitor-git](https://aur.archlinux.org/packages/pantheon-system-monitor-git/) in the **AUR**:

`$ aurman -S pantheon-system-monitor-git`

PS: 
* I added your donation link in package description.
* Monitor name isn't available

**Comment by stsdc** [comment]
Wow, that's awesome! thanks!
