### ISSUE TITLE
Publish in Juno!

### ISSUE THREAD

**Issue by danrabbit** [stsdc/monitor#57]
Our [second Juno Developer Preview](https://medium.com/elementaryos/developer-preview-juno-beta-2-is-out-418f5037e9bb) is out and Juno's big debut is just around the corner! We'd love to see your app in AppCenter on release day.

Check out this [Developer Tips](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7) article to learn how to publish your app for elementary OS 5.

If you need help updating your app for Juno, we’re always standing by in [Gitter](https://gitter.im/elementary/houston) and the [Community Slack](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) to help wherever we can.

**Comment by stsdc** [comment]
Waiting for payment to buy parts for PC. Then I'll install Juno and rebuild Monitor. Don't have much time to develop this project, but I'll try to publish Monitor for Juno ASAP.

If You want to support me feel free to tip a few bucks [here](https://paypal.me/stsdc/10). Or make a PR

**Comment by cassidyjames** [comment]
@stsdc it appears to build and run fine here on Juno. I'll submit a PR with some deprecation fixes.
