### ISSUE TITLE
Few improvements

### ISSUE THREAD

**Issue by Dirli** [stsdc/monitor#66]
How do you look at wingpanel-indicator support?

According to the link a screenshot with option of the monitor of resources. If satisfied, I pullrequest it. True to the end have not completed yet:
 https://ibb.co/C0B9bFP

**Comment by stsdc** [comment]
Hello @Dirli !
Wingpanel indicator support is already written: you can check the **indocator** branch. However I it is blocked by #49 

I don't know is it a mockup or a really working app, but this screenshot looks really cool!
I thought about adding a resources tab and it definitely will happen in future. But right now Monitor has a few [bugs](https://github.com/stsdc/monitor/issues?q=is%3Aissue+is%3Aopen+label%3Abug) that prevent me from adding more features. I afraid that if I will add more options it will be harder to fix these bugs.

**Comment by Dirli** [comment]
I understand you, I will follow. The processes I am interested in are less than the resources consumed (gento, compilation), so I’ll publish my version for now, if you don’t mind (some code may be useful to you)))

**Comment by stsdc** [comment]
@Dirli no problem
