### ISSUE TITLE
Add appdata to be translated

### ISSUE THREAD

**Issue by NathanBnm** [stsdc/monitor#68]
Translating `appdata.xml` file will help people to know about your app in the AppCenter. For example mostly French users won't download the app if it's description is in English, 'cause they will think that the app isn't translated and won't take time to read if its not translated.

**Comment by ryonakano** [comment]
Actually, I've already make appdata.xml file translatable in f878a1807b795617dc8e8ae358d7ac393eb3e146, so it should be shown in your language if you add your translation in `po/extra/fr.po` and Stanisław released a new version of Monitor.

**Comment by NathanBnm** [comment]
Sorry I didn't notice, thanks I'll translate it now so
