### ISSUE TITLE
Screenshot must be in English

### ISSUE THREAD

**Issue by stsdc** [stsdc/monitor#90]

**Comment by amz-x** [comment]
I am attaching an English screenshot. Let me know if I should create a PR and / or resize the image.

![com github stsdc monitor screenshot](https://user-images.githubusercontent.com/18249234/56159589-64738880-5fc5-11e9-9457-30fae7f27957.png)

**Comment by stsdc** [comment]
I think the size is ok. I will accept a PR. Thanks!
