### ISSUE TITLE
Validating appdata.xml results in error

### ISSUE THREAD

**Issue by amz-x** [stsdc/monitor#96]
Trying to validate **com.github.stsdc.monitor.appdata.xml.in** results in an error.

Executing in data directory:
```
appstream-util validate-relax --nonet com.github.stsdc.monitor.appdata.xml.in
```

Results in:
```
com.github.stsdc.monitor.appdata.xml.in: Error on line 18 char 11: <description> already set '​' and tried to replace with '
      '
```

Issue currently present in 0.4.4 release & master branch.

**Comment by stsdc** [comment]
Strange. How it passed Houston tests then? 🤔

**Comment by amz-x** [comment]
Apologies, after diving in a bit further. I see that Houston is using appsteamcli instead of appstream-util.
Validating with appstreamcli works. There is an ongoing issue [here](https://github.com/AppImage/AppImageKit/issues/603)

**Comment by stsdc** [comment]
So is it really an issue of Monitor? If not then it should be closed.
